sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t walter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true walter/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-west-2"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-west-2-412533004980"
 bucket_path: 'docker'
 on:
   branch: main
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"